# How to use:
#
# docker-compose -f ./docker-compose.yml
#
# psql -h 10.10.0.1 test_test test

version: '2'
services:
  db:
    image: ${registry.host}/pingbus/db:${snapshot}
    environment:
      POSTGRES_DB: pingbus
      POSTGRES_USER: asharov
      POSTGRES_PASSWORD: Password1234
    ports:
      - "5432:5432"
    volumes:
      - /Users/asharov/oop-uni:/var/lib/postgresql/data
    networks:
      - pingbus

  app:
    image: ${registry.host}/pingbus/app:${snapshot}
    ports:
      - "8080:8080"
    networks:
      - pingbus

networks:
  pingbus:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24
          gateway: 10.10.0.254